FROM golang:1.16.5

ENV VERSION v1.0.22
ENV GOCACHE /tmp
WORKDIR /go/src/github.com/josiokoko/movies-parser

RUN go get -u golang.org/x/lint/golint

COPY . .
COPY main.go go.mod ./
RUN go mod tidy
RUN go get -v 
