FROM golang:1.13.4

ENV VERSION v1.0.22
ENV GOCACHE /tmp
WORKDIR /go/src/github/josiokoko/movies-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/v0.1.17/nancy-linux.amd64-v0.1.17 -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy
RUN go get -u golang.org/x/lint/golint

COPY . .

RUN go get -v 

